[pytest]

markers =
    headed: run test in headed mode (browser visible)
    chromium: run test in chromium browser
    firefox: run test in firefox browser
    webkit: run test in webkit browser
    browser: specify browser for test
    slow: slow test
    skip: skip test
    debug: run test in debug mode
    dependency: mark test as having dependencies
    smoke: mark test as smoke test
    regression: mark test as regression test
    feature: mark test as feature test
    scenario: mark test as scenario test
    severity: mark test with severity level (blockeante, critico, bajo)

addopts = --tb=short --slowmo=300 --headed --browser=chromium -v  --html=./Test_web/reportes/pytest-html/report.html --self-contained-html --alluredir=./Test_web/reportes/allure-resultados --clean-alluredir

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*